#!/bin/sh
###
# unsharedfs-prepare
# Copyright (c) 2014 Johannes Zarl
###
UNSHAREDFS_PREPARE_VERSIONSTRING="unsharedfs-prepare 1.0"

ACT=
ALL_USERS=
CREATE_DEFAULT=
FORCE_NON_EMPTY_ROOTDIR=
ROOTDIR=
UID_MIN=0
UID_MAX=0
USE_GID=
USE_UID_MIN=
USE_UID_MAX=
USERLIST=

print_version()
{
	cat <<EOF
$UNSHAREDFS_PREPARE_VERSIONSTRING

Copyright (C) 2014 Johannes Zarl
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Written by Johannes Zarl.

EOF
}
print_usage()
{
	cat <<EOF
Usage: $0 ROOTDIRECTORY [OPTIONS] USER [ ... USER]
       $0 ROOTDIRECTORY [OPTIONS] -a [uid_min [uid_max]]

Create a directory structure suitable for mounting as an unsharedfs file system.

   ROOTDIRECTORY    Empty directory in which the subdirectories will be created.
   USER             Username to include.

Options:
   -a [uid_min [uid_max]]
                    Create directories for all users (as seen by ``getent passwd'')
                    If bounds are given, only users with an uid greater or equal to uid_min
                    and less or equal to uid_max are considered.
   -d               Also create a directory "default".
   -f, --force-non-empty-rootdir
                    Allow a non-empty root directory.
   -g, --use-gid    Create a directory structure usable with the unsharedfs option "--use-gid".
   -n, --no-act     Don't actually create any directory, just print what would be done.

EOF
}

## check_rootdir ROOTDIR
# return 0 if the rootdir seems fine, 1 otherwise.
check_rootdir()
{
	if [ ! -d "$1" ]
	then
		echo "Root directory does not exist!" >&2
		return 1
	fi
	if [ -z "$FORCE_NON_EMPTY_ROOTDIR" -a `ls -1 "$1" |wc -l` != "0" ]
	then
	   echo "Root directory is not empty!" >&2
	   return 1
	fi
}

## get_id USERNAME
# Print the numeric [gu]id for USERNAME
# return 0 on success, 1 if the user name is not found.
get_id()
{
	if [ -z "$USE_GID" ]
	then
		id -u "$1"
	else
		id -g "$1"
	fi
}

## set_ownership DIRECTORY USER
# Set the (group or user) ownership on DIRECTORY to USER.
set_ownership()
{
	if [ -z "$USE_GID" ]
	then
		$ACT chown "$2" "$1"
	else
		if grpid=`id -gn "$2"`
		then
			$ACT chgrp "$grpid" "$1"
		else
			echo "Could not get group name for user $2!" >&2
			return 1
		fi
	fi
}

## create_dirs ROOTDIR
# Read user names from stdin (one per line) and create a [gu]id directory for each name.
create_dirs()
{
	while read user
	do
		if theid=`get_id "$user"`
		then
			# quietly skip existing directories
			if [ ! -x "$1/$theid" ]
			then
				$ACT mkdir "$1/$theid"
				set_ownership "$1/$theid" "$user"
			fi
		else
			echo "Warning: could not find numeric id for user $user!" >&2
		fi
	done
}


### Parse commandline:

for arg
do
	case "$arg" in
	-a)
		ALL_USERS=1
		;;
	-d)
		CREATE_DEFAULT=1
		;;
	-f|--force-non-empty-rootdir)
		FORCE_NON_EMPTY_ROOTDIR=1
		;;
	-g|--use-gid)
		USE_GID=yes
		;;
	-h|--help)
		print_usage
		exit 0
		;;
	-n|--no-act)
		ACT="echo NOT executing: "
		;;
	-*)
		echo "Invalid argument: $arg" >&2
		print_usage
		exit 1
		;;
	*)
		# first non-option argument is root dir:
		if [ -z "$ROOTDIR" ]
		then
			ROOTDIR="$arg"
		else
			# gather other non-option arguments in USERLIST
			# if "-a" was set, we will parse this later on...
			USERLIST="$USERLIST $arg"
		fi
		;;
	esac
done

if [ -n "$ALL_USERS" ]
then
	for arg in $USERLIST
	do
		if [ -z "$USE_UID_MIN" ]
		then
			USE_UID_MIN=1
			UID_MIN="$arg"
		else
			if [ -z "$USE_UID_MAX" ]
			then
				USE_UID_MAX=1
				UID_MAX="$arg"
			else
				echo "Too many arguments to ``-a'' parameter!" >&2
				print_usage
				exit 1
			fi
		fi
	done
fi

if [ \( -z "$ROOTDIR" \) -o \( -z "$ALL_USERS" -a -z "$USERLIST" \) ]
then
	print_usage
	exit 1
fi

check_rootdir "$ROOTDIR" || exit 2

if [ -z "$ALL_USERS" ]
then
	# create dirs for specified users:
	for u in $USERLIST
	do
		echo $u
	done | create_dirs "$ROOTDIR"
else
	# create dirs for all users:
	getent passwd | while IFS=: read name x uid rest
	do
		if [ -z "$USE_UID_MIN" -o \( "$uid" -ge "$UID_MIN" -a \( -z "$USE_UID_MAX" -o "$uid" -le "$UID_MAX" \) \) ]
		then
			echo $name
		fi
	done | create_dirs "$ROOTDIR"
fi
